runtime: python310
# env: flex
#service: rfptesting456
service: #add your service name
instance_class: F4_1G
automatic_scaling:
  min_instances: 1
  target_cpu_utilization: 0.65
readiness_check:
  path: "/"
  app_start_timeout_sec: 1000
resources:
  cpu: 4
  memory_gb: 22
  disk_size_gb: 120
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
